FROM rust:buster

RUN apt update && apt-get install -y \
    sudo \
    curl \
    vim

ARG UID=1000
ARG GID=1000
ARG USERNAME=user

# Create a new user with the provided UID and GID
RUN groupadd -g $GID user && \
    useradd -m -u $UID -g $GID -s /bin/bash $USERNAME

WORKDIR /home/$USERNAME/app/

# Copy the Cargo.toml and Cargo.lock to fetch dependencies
COPY Cargo.toml Cargo.lock ./
RUN mkdir src
# Create a dummy main.rs to satisfy the build for dependency fetching.
# This step helps with Docker caching so you don't re-download dependencies unless the Cargo files change.
RUN echo "fn main() {}" > src/main.rs
RUN cargo build

USER $USERNAME
