FROM rust:buster

RUN apt update && apt-get install -y \
    sudo \
    curl \
    vim

ARG UID=1000
ARG GID=1000
ARG USERNAME=user

# Create a new user with the provided UID and GID
RUN groupadd -g $GID user && \
    useradd -m -u $UID -g $GID -s /bin/bash $USERNAME

RUN usermod -aG sudo $USERNAME
RUN echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER $USERNAME

WORKDIR /home/$USERNAME/app/
RUN sudo chown -R $(id -u):$(id -g) /home/$USERNAME/

# Copy the Cargo.toml and Cargo.lock to fetch dependencies
COPY Cargo.toml Cargo.lock ./
# Create a dummy main.rs to satisfy the build for dependency fetching.
# This step helps with Docker caching so you don't re-download dependencies unless the Cargo files change.
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build

